import mongoose from "mongoose";

const sDataSchema = new mongoose.Schema(
  {
    _id: {
      type: mongoose.Schema.Types.ObjectId, // Correct type for MongoDB _id
      required: true,
      auto: true, // Automatically generated by MongoDB if not provided
    },
    Date: {
      type: Date,
      required: true,
    },
    StudentName: {
      type: String,
      required: true,
    },
    StudentPhoto: {
      type: String,
      required: true,
    },
    Class: {
      type: String,
      required: true,
    },
    sIndexNum: {
      type: Number,
      required: true,
    },
    Reason: {
      type: String,
      required: true,
    },
    TeacherID: {
      type: String,
      required: true,
    },
    Agreement: {
      type: String,
      required: true,
    },
    AgreementEndDate: {
      type: Date,
      required: true,
    },
    ObserverTeacherID: {
      type: String,
      required: true,
    },
    Isactive: {
      type: Boolean,
      required: true,
    },
    // StudentPhotoUrl: {
    //   type: String,
    //   required: true,
    // },
  },
  {
    timestamps: true,
  }
);

const StData = mongoose.model("StData", sDataSchema);

export default StData;
